apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hello-world
  templates:
  - name: hello-world
    steps:
    - - name: step-1
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello from step 1"}]
    - - name: step-2
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello from step 2"}]
    - - name: step-3
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello from step 3"}]

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
