name: Submit Argo Workflow

on:
  push:
    branches:
      - main  # Adjust to your main branch name or other branches

jobs:
  submit-workflow:
    runs-on: ubuntu-latest
    env:
      ARGO_SERVER: ${{ secrets.ARGO_SERVER }}
      ARGO_HTTP1: true
      ARGO_SECURE: true
      ARGO_BASE_HREF: ''
      ARGO_TOKEN: ${{ secrets.ARGO_TOKEN }}
      ARGO_NAMESPACE: argo  # Replace with your desired namespace
      KUBECONFIG: /dev/null

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Argo CLI
        run: |
          curl -sLO https://github.com/argoproj/argo/releases/latest/download/argo-linux-amd64.gz
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          sudo mv argo-linux-amd64 /usr/local/bin/argo

      - name: Set up environment variables
        run: |
          echo "ARGO_SERVER=$ARGO_SERVER" >> $GITHUB_ENV
          echo "ARGO_HTTP1=$ARGO_HTTP1" >> $GITHUB_ENV
          echo "ARGO_SECURE=$ARGO_SECURE" >> $GITHUB_ENV
          echo "ARGO_BASE_HREF=$ARGO_BASE_HREF" >> $GITHUB_ENV
          echo "ARGO_TOKEN=$ARGO_TOKEN" >> $GITHUB_ENV
          echo "ARGO_NAMESPACE=$ARGO_NAMESPACE" >> $GITHUB_ENV
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
          cat $GITHUB_ENV  # Output environment variables for debugging

      - name: Submit Argo Workflow
        run: |
          argo submit my-workflow.yaml
        # Replace my-workflow.yaml with the path to your actual workflow YAML file
