name: Java CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Compile Java code
      run: javac Main.java

    - name: Run Java file
      run: java Main

    - name: Build JAR
      run: |
        mkdir -p target
        echo "Main-Class: Main" > manifest.txt
        jar cfm target/app.jar manifest.txt Main.class

    - name: Build Docker image
      run: docker build -t java-app:latest .

    - name: Run Docker container
      run: docker run --name java-app-container java-app:latest
