name: Submit Argo Workflow

on:
  push:
    branches:
      - main

jobs:
  submit-argo-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install HTTPie
      run: |
        python -m pip install httpie

    - name: Submit Argo Workflow
      env:
        ARGO_SERVER: ${{ secrets.ARGO_SERVER }}
        ARGO_TOKEN: ${{ secrets.ARGO_TOKEN }}
      run: |
        http --auth-type=jwt --auth="${{ secrets.ARGO_TOKEN }}" \
        POST "${{ secrets.ARGO_SERVER }}/api/v1/workflows/argo/submit" \
        workflow=@argo-workflow.yml
